### ISSUE TITLE
Rename command

### ISSUE THREAD

**Issue by B1ackAnge1** [qogusdn1017/BaeHyeonWooPL#10]
Suggest that use `rmgod` from `removegod ` for command.
It is more shorter and much easier then `removegod`

**Comment by qogusdn1017** [comment]
Trying to change the lang to Kotlin.

Please wait while I edit the Main code or [HappyAndJust](https://github.com/HappyAndJust) trys the pull request again.

You can close the issue if you want. But I'm not suggesting it ; cuz I have bad memories lmao

**Comment by qogusdn1017** [comment]
Done with it.
